[package]
name = "calcu_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitflags = "2.4.1"
calcurs_macros = { path = "macros" }
# egg = {version = "0.9.5", features = ["wasm-bindgen"]}

smallvec = "1.13.2"
indexmap = "2.2.6"
fxhash = "0.2.1"

ordered-float = "4.2.0"
malachite = "0.4.7"
num = "0.4.3"
num-bigint = "0.4"
num-traits = "0.2"

symbol_table = { version = "0.3.0", features = ["global"]}

env_logger = { version = "0.11.3", default-features = false }
log = "0.4.17"
paste = "1.0.15"

[dev-dependencies]
test-case = "3.3.1"

[features]
# forces the use of indexmaps over hashmaps
# deterministic = []
