[package]
name = "calcurus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
calcurus_macros = {package = "macros", path = "macros" }
calcurus_internals = {package = "internals", path = "internals" }
# calcurus_internals = { path = "internals" }
