[package]
name = "calcu-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
paste = "1.0.14"

[dev-dependencies]
pretty_assertions = "1.4.0"
test-case = "3.2.1"
