[package]
name = "calcu_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
calcurs_macros = { path = "macros" }
egg = {version = "0.9.5", features = ["wasm-bindgen"]}
env_logger = "0.9.3"
ordered-float = "4.2.0"
num = "0.4.3"
malachite = "0.4.7"
smallvec = "1.13.2"
hashbrown = "0.14.5"

[dev-dependencies]
pretty_assertions = "1.4.0"
test-case = "3.2.1"
